import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, describe, expect, it } from 'vitest';

// Checks on the distribution bundle (plugin/bin/roadmap-lint.js).
// The bundle is a committed generated file (regenerated by scripts/build-plugin.mjs).
// Its freshness is verified byte for byte by `pnpm run build:plugin -- --check` (the same manual convention as regen:fixtures).

const repoRoot = fileURLToPath(new URL('../../..', import.meta.url));
const binDir = path.join(repoRoot, 'plugin', 'bin');
const bundlePath = path.join(binDir, 'roadmap-lint.js');

// Self-containment is checked in an isolated copy outside the repository (it must depend on neither
// node_modules nor the root package.json's type: module — the same conditions as an installed plugin directory)
const isolatedDir = mkdtempSync(path.join(tmpdir(), 'rdd-kit-bundle-'));
if (existsSync(binDir)) cpSync(binDir, isolatedDir, { recursive: true });
afterAll(() => rmSync(isolatedDir, { recursive: true, force: true }));

function runIsolated(args: string[]) {
  return spawnSync(process.execPath, [path.join(isolatedDir, 'roadmap-lint.js'), ...args], {
    encoding: 'utf8',
    cwd: isolatedDir,
  });
}

it('precondition: the bundle is committed (run pnpm run build:plugin when it is not)', () => {
  expect(existsSync(bundlePath)).toBe(true);
  expect(existsSync(path.join(binDir, 'package.json'))).toBe(true);
});

describe('the distribution bundle', () => {
  it('is a single file with a shebang, with the CJS reading pinned by a type pin', () => {
    expect(readFileSync(bundlePath, 'utf8').startsWith('#!/usr/bin/env node\n')).toBe(true);
    expect(JSON.parse(readFileSync(path.join(binDir, 'package.json'), 'utf8'))).toEqual({
      type: 'commonjs',
    });
  });

  it('reports the version of packages/cli/package.json from --version (injected through define)', () => {
    const { version } = JSON.parse(
      readFileSync(path.join(repoRoot, 'packages', 'cli', 'package.json'), 'utf8'),
    ) as { version: string };
    const res = runIsolated(['--version']);
    expect(res.status).toBe(0);
    expect(res.stdout.trim()).toBe(version);
  });

  it('ships the license files beside it: plugin/LICENSE is the root LICENSE, and the third-party list names exactly the packages the bundle inlines', () => {
    const pluginDir = path.join(repoRoot, 'plugin');
    expect(readFileSync(path.join(pluginDir, 'LICENSE')).equals(readFileSync(path.join(repoRoot, 'LICENSE')))).toBe(true);

    // Two independent derivations of "what is inlined": the list comes from esbuild's metafile at build
    // time, and the bundle itself carries a `// node_modules/.pnpm/<store dir>/node_modules/<package>/<file>`
    // comment above every inlined module. The version is read from that package directory's package.json —
    // the store directory name carries it too, but a peer suffix (`_<peer>@<version>`) or pnpm's shortening
    // of a long name can hide it
    const bundleText = readFileSync(bundlePath, 'utf8');
    const inlined = new Set<string>();
    for (const match of bundleText.matchAll(/^\s*\/\/ (node_modules\/\.pnpm\/[^/\n]+\/node_modules\/((?:@[^/\n]+\/)?[^/\n]+))\//gmu)) {
      const { version } = JSON.parse(readFileSync(path.join(repoRoot, match[1] as string, 'package.json'), 'utf8')) as {
        version: string;
      };
      inlined.add(`${match[2] as string} ${version}`);
    }
    expect(inlined.size).toBeGreaterThan(0);

    const list = readFileSync(path.join(pluginDir, 'THIRD-PARTY-LICENSES.txt'), 'utf8');
    expect(list).not.toContain('\r');
    const entries = [...list.matchAll(/^(\S+) (\d+\.\d+\.\d+\S*) — (.+)$/gmu)];
    expect(new Set(entries.map((match) => `${match[1] as string} ${match[2] as string}`))).toEqual(inlined);
    expect(list).toContain(`Packages: ${entries.length}.`);

    // Every entry carries what its license requires a copy to carry: the copyright line, and the
    // permission notice of the declared license (a license text, or the standard text written for a
    // package that ships none). A declared license this map does not know fails here until it is added
    const PERMISSION_NOTICE: Record<string, string> = {
      MIT: 'Permission is hereby granted, free of charge',
      ISC: 'Permission to use, copy, modify, and/or distribute this software',
    };
    const blocks = list.split(/^=+\n\S+ \d+\.\d+\.\d+\S* — .+\n=+\n/mu).slice(1);
    expect(blocks.length).toBe(entries.length);
    const declared = new Set<string>();
    for (const [index, block] of blocks.entries()) {
      const name = entries[index]?.[1] as string;
      const id = (entries[index]?.[3] as string).replace(/\s*\(.*\)$/u, '');
      declared.add(id);
      expect(PERMISSION_NOTICE[id], `${name}: declared license ${id}`).toBeDefined();
      // The holder's line, not a wrapped "copyright notice and this permission notice" of the text itself
      expect(block, `${name}: copyright line`).toMatch(/^(?:\s*\S+: )?Copyright\b(?! notice)/mu);
      expect(block, `${name}: permission notice`).toContain(PERMISSION_NOTICE[id]);
    }
    // The READMEs name the licenses the bundle carries
    for (const document of ['README.md', path.join('plugin', 'README.md')]) {
      const text = readFileSync(path.join(repoRoot, document), 'utf8');
      for (const id of declared) expect(text, `${document} names ${id}`).toContain(id);
    }
  });

  it('lints the valid corpus from the isolated copy with no diagnostics (self-contained)', () => {
    // The GIT rules judge the host repository's git state rather than the corpus, so lint-corpus.config.json
    // takes them out of scope (the same config the corpus checks and lint:corpus use)
    const res = runIsolated([
      path.join(repoRoot, 'fixtures', 'valid'),
      '--config',
      path.join(repoRoot, 'lint-corpus.config.json'),
      '--format',
      'json',
    ]);
    expect(res.status).toBe(0);
    const report = JSON.parse(res.stdout) as { diagnostics: { rule: string }[] };
    expect(report.diagnostics).toEqual([]);
  });
});

describe('the npm channel', () => {
  const cliDir = path.join(repoRoot, 'packages', 'cli');
  const cjsPath = path.join(cliDir, 'bundle', 'roadmap-lint.cjs');

  it('package.json: bin points at bundle/roadmap-lint.cjs, there are no runtime dependencies, and files holds the bundle, the two license files, and the copyright notice alone', () => {
    const pkg = JSON.parse(readFileSync(path.join(cliDir, 'package.json'), 'utf8')) as {
      bin: Record<string, string>;
      files: string[];
      dependencies?: Record<string, string>;
    };
    expect(pkg.bin).toEqual({ 'roadmap-lint': 'bundle/roadmap-lint.cjs' });
    // LICENSE is a generated copy of the root file and is listed explicitly: pnpm's own copying of the
    // workspace LICENSE is skipped as soon as any packed file name contains "LICENSE"
    expect(pkg.files).toEqual(['bundle', 'LICENSE', 'NOTICE', 'THIRD-PARTY-LICENSES.txt']);
    expect(pkg.dependencies).toBeUndefined();
  });

  it('packs exactly the bundle, the two license files, the copyright notice, and package.json (npm pack --dry-run)', () => {
    // Needs npm on the PATH. One command string through the shell, so the shell resolves npm.cmd / npm.exe
    // on Windows without a deprecation warning; --ignore-scripts keeps a lifecycle script's output out of stdout
    const res = spawnSync('npm pack --dry-run --json --ignore-scripts', { encoding: 'utf8', cwd: cliDir, shell: true });
    expect(res.error, 'npm could not be started (is it on the PATH?)').toBeUndefined();
    expect(res.status, res.stderr).toBe(0);
    const [packed] = JSON.parse(res.stdout) as { files: { path: string }[] }[];
    expect(packed?.files.map((file) => file.path).sort()).toEqual([
      'LICENSE',
      'NOTICE',
      'THIRD-PARTY-LICENSES.txt',
      'bundle/roadmap-lint.cjs',
      'package.json',
    ]);
  });

  it('keeps bundle/roadmap-lint.cjs and the two license files byte-identical to the plugin copies, and runs from inside a type: module package', () => {
    expect(readFileSync(cjsPath).equals(readFileSync(bundlePath))).toBe(true);
    expect(readFileSync(path.join(cliDir, 'LICENSE')).equals(readFileSync(path.join(repoRoot, 'LICENSE')))).toBe(true);
    expect(
      readFileSync(path.join(cliDir, 'THIRD-PARTY-LICENSES.txt')).equals(
        readFileSync(path.join(repoRoot, 'plugin', 'THIRD-PARTY-LICENSES.txt')),
      ),
    ).toBe(true);
    const res = spawnSync(process.execPath, [cjsPath, '--version'], { encoding: 'utf8' });
    expect(res.status).toBe(0);
    expect(res.stdout.trim()).toMatch(/^\d+\.\d+\.\d+$/);
  });
});
